---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-backend
  namespace: todolist
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: todolist-backend
  template:
    metadata:
      labels:
        app: todolist-backend
    spec:
      containers:
      - name: todolist-backend
        image: ghcr.io/redxops/projet-devops-backend:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: DB_USER
          - name: DB_DIALECT
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: DB_DIALECT
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: PORT
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todolist-secret
                key: DB_PASSWORD