---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todolist-mysql
  namespace: todolist
spec:
  serviceName: todolist-mysql
  replicas: 1
  selector:
    matchLabels:
      app: todolist-mysql
  template:
    metadata:
      labels:
        app: todolist-mysql
    spec:
      containers:
      - name: todolist-mysql
        image: mysql:9.7.2@sha256:257388edf9c84dbc04c763625446d5f3fa6ed60d1b0873bc552c614ba0a7ab4e
        resources:
          limits:
            memory: "4Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql/
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: DB_NAME 
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: DB_USER
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: todolist-config
                key: MYSQL_RANDOM_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todolist-secret
                key: DB_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi